ci(changeset): disallow major release [AR-44378]

diff --git a/.github/workflows/changeset.yml b/.github/workflows/changeset.yml
--- a/.github/workflows/changeset.yml
+++ b/.github/workflows/changeset.yml
@@ -54,3 +54,32 @@ jobs:
       # See: https://github.com/changesets/changesets/blob/main/docs/automating-changesets.md#blocking
       - name: Run Changesets
         run: pnpm changeset status --since origin/main
+
+  disallow-major:
+    - name: Disallow Major Release
+      runs-on: ubuntu-latest
+
+      permissions:
+        contents: read
+
+      # Skip opted out PRs, and release PRs
+      if: |
+        ! contains(github.event.pull_request.labels.*.name, 'skip changelog') &&
+        ! (github.event.pull_request.title == 'chore(release): publish' && github.event.pull_request.user.login == 'github-actions[bot]')
+
+      steps:
+        - name: Checkout source code
+          uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+          with:
+            fetch-depth: 0
+            persist-credentials: false
+
+        - name: Check for Major Changeset
+          run: |
+            STATUS_OUTPUT=$(pnpm changeset status --since origin/main)
+            MAJOR_PATTERN="info Packages to be bumped at major:"
+
+            if [[ "$STATUS_OUTPUT" == *"$MAJOR_PATTERN"* ]]; then
+              echo "Error: Major changesets are not allowed. Did you mean to create a minor or patch changeset instead?";
+              exit 1;
+            fi
